.PHONY: build release release-musl platform-audit test lint fmt clippy install harden unit clean help

CARGO ?= cargo
# Static musl target (Alpine). musl-gcc comes from the `musl-tools` package and
# targets the host arch, so this works natively on x86_64 and aarch64 runners.
MUSL_TARGET ?= $(shell uname -m)-unknown-linux-musl

## Build (debug)
build:
	$(CARGO) build --workspace

## Build (release, native glibc — Debian/RHEL/Wolfi)
release:
	$(CARGO) build --release -p legionr-cli

## Build static musl release (Alpine). Needs: rustup target + musl-tools.
release-musl:
	rustup target add $(MUSL_TARGET)
	CC_$(subst -,_,$(MUSL_TARGET))=musl-gcc \
	CARGO_TARGET_$(shell echo $(MUSL_TARGET) | tr 'a-z-' 'A-Z_')_LINKER=musl-gcc \
	$(CARGO) build --release -p legionr-cli -p legionr-fim --target $(MUSL_TARGET)
	@echo "static binaries → target/$(MUSL_TARGET)/release/{legionr,legionr-fim}"

## Audit this host's platform capabilities (eBPF/nft/sampler/systemd).
platform-audit:
	@./scripts/platform-audit.sh

## Run all tests
test:
	$(CARGO) test --workspace

## fmt check + clippy (matches CI: -D warnings)
lint: fmt clippy

fmt:
	$(CARGO) fmt --all -- --check

clippy:
	$(CARGO) clippy --all-targets --all-features -- -D warnings

## Format the tree in place
fix:
	$(CARGO) fmt --all

## Install on this host (creates the legionr user, fetches the runner)
install:
	sudo ./scripts/install.sh

## Apply host hardening (systemd + sysctl + nftables egress allowlist)
harden:
	sudo ./scripts/harden.sh

## Regenerate the reference systemd unit from the binary
unit: build
	@tmp=$$(mktemp -d); \
	LEGIONR_DATA_DIR=/opt/legion-runner ./target/debug/legionr --config $$tmp/c.json provision tbgor/legion_runner --no-probe >/dev/null; \
	{ echo "# Reference copy — the canonical unit is generated by \`legionr harden --install\`."; \
	  echo "# Regenerate: legionr --config /etc/legion-runner/<name>.json harden"; echo "#"; \
	  LEGIONR_DATA_DIR=/opt/legion-runner ./target/debug/legionr --config $$tmp/c.json harden \
	    | awk '/legionr@.service/{f=1;next} /sysctl\.d/{f=0} f'; } > systemd/legionr@.service; \
	rm -rf $$tmp; echo "regenerated systemd/legionr@.service"

## Clean build artifacts
clean:
	$(CARGO) clean

## Show this help
help:
	@echo "Legion Runner — targets:"
	@echo "  make build         Debug build"
	@echo "  make release       Release build of legionr (native glibc)"
	@echo "  make release-musl  Static musl build (Alpine), legionr + legionr-fim"
	@echo "  make platform-audit  Probe this host's capabilities"
	@echo "  make test          Run workspace tests"
	@echo "  make lint       fmt --check + clippy -D warnings"
	@echo "  make install    Install on this host (sudo)"
	@echo "  make harden     Apply host hardening (sudo)"
	@echo "  make unit       Regenerate systemd/legionr@.service"
	@echo "  make clean      Remove build artifacts"
