.PHONY: build release test lint fmt clippy install harden unit clean help

CARGO ?= cargo

## Build (debug)
build:
	$(CARGO) build --workspace

## Build (release)
release:
	$(CARGO) build --release -p legionr-cli

## Run all tests
test:
	$(CARGO) test --workspace

## fmt check + clippy (matches CI: -D warnings)
lint: fmt clippy

fmt:
	$(CARGO) fmt --all -- --check

clippy:
	$(CARGO) clippy --all-targets --all-features -- -D warnings

## Format the tree in place
fix:
	$(CARGO) fmt --all

## Install on this host (creates the legionr user, fetches the runner)
install:
	sudo ./scripts/install.sh

## Apply host hardening (systemd + sysctl + nftables egress allowlist)
harden:
	sudo ./scripts/harden.sh

## Regenerate the reference systemd unit from the binary
unit: build
	@tmp=$$(mktemp -d); \
	LEGIONR_DATA_DIR=/opt/legion-runner ./target/debug/legionr --config $$tmp/c.json provision tbgor/legion_runner --no-probe >/dev/null; \
	{ echo "# Reference copy — the canonical unit is generated by \`legionr harden --install\`."; \
	  echo "# Regenerate: legionr --config /etc/legion-runner/<name>.json harden"; echo "#"; \
	  LEGIONR_DATA_DIR=/opt/legion-runner ./target/debug/legionr --config $$tmp/c.json harden \
	    | awk '/legionr@.service/{f=1;next} /sysctl\.d/{f=0} f'; } > systemd/legionr@.service; \
	rm -rf $$tmp; echo "regenerated systemd/legionr@.service"

## Clean build artifacts
clean:
	$(CARGO) clean

## Show this help
help:
	@echo "Legion Runner — targets:"
	@echo "  make build      Debug build"
	@echo "  make release    Release build of legionr"
	@echo "  make test       Run workspace tests"
	@echo "  make lint       fmt --check + clippy -D warnings"
	@echo "  make install    Install on this host (sudo)"
	@echo "  make harden     Apply host hardening (sudo)"
	@echo "  make unit       Regenerate systemd/legionr@.service"
	@echo "  make clean      Remove build artifacts"
